# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

name: Taxicity-$(Build.BuildId)

stages:
  - stage: Build
    displayName: Build and Push stage
    jobs:
    - job:
      displayName: Build job
      pool:
        name: ProdPool
      steps:
      # - task: Docker@2
      #   displayName: Build and Push an image to the container registry
      #   inputs:
      #     containerRegistry: $(docker_registry)
      #     repository: $(registry_repo)
      #     command: buildAndPush
      #     dockerfile: '**/Dockerfile'
      #     tags: |
      #       $(Build.BuildNumber)
            
      - script: |
          npm install --legacy-peer-deps
          mv packages/react-app/.env.template packages/react-app/.env
          cd packages/react-app
        displayName: Installing dependencies
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: packages/react-app/.next
          ArtifactName: 'tax-web-site'
          publishLocation: Container          