# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

name: Taxicity-$(Build.BuildId)

stages:
  - stage: Build
    displayName: Build and Push stage
    jobs:
    - job:
      displayName: Build job
      pool:
        name: ProdPool
      steps:
      - task: Docker@2
        displayName: Build and Push an image to the container registry
        inputs:
          containerRegistry: 'docker_hub_connection-hackathon'
          repository: 'ranger03/taxicity'
          command: buildAndPush
          dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildNumber)
          