# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
- group: NextJsEnvironmentVariables

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install --legacy-peer-deps
  displayName: 'installing dependencies'

- script: |
    npm run react-app:build
  displayName: 'running build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'packages/react-app/out'
    ArtifactName: 'dev'
    publishLocation: 'Container'